-- Just Company private operations schema for Supabase
create extension if not exists pgcrypto;
create type public.jc_request_status as enum ('new','under_review','verification_required','approved','companion_search','companion_accepted','awaiting_payment','payment_verified','confirmed','completed','cancelled','incident_review');
create type public.jc_booking_status as enum ('draft','awaiting_payment','payment_verified','confirmed','in_progress','completed','cancelled','incident_review');
create type public.jc_channel as enum ('telegram','whatsapp','email');
create table if not exists public.jc_admin_users (user_id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now());
create table if not exists public.jc_customers (id uuid primary key default gen_random_uuid(), full_name text not null, email text, phone text, preferred_channel jc_channel, for_self boolean not null default true, verification_status text not null default 'pending', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jc_requests (id uuid primary key default gen_random_uuid(), reference text unique not null default ('JC-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))), customer_id uuid not null references public.jc_customers(id), activity text not null, requested_date date, requested_start_time time, duration_hours numeric(4,1), general_area text, destination text, spending_type text, companion_cost_plan text, notes text, status jc_request_status not null default 'new', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jc_request_attachments (id uuid primary key default gen_random_uuid(), request_id uuid not null references public.jc_requests(id) on delete cascade, storage_path text not null, attachment_type text not null, created_at timestamptz not null default now());
create table if not exists public.jc_companions (id uuid primary key default gen_random_uuid(), full_name text not null, email text, phone text, telegram_chat_id text, telegram_username text, whatsapp_jid text, preferred_channel jc_channel not null default 'telegram', areas_served text[], availability_notes text, interests text[], hourly_rate numeric(10,2), screening_status text not null default 'pending', active boolean not null default true, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jc_opportunities (id uuid primary key default gen_random_uuid(), request_id uuid not null references public.jc_requests(id) on delete cascade, companion_id uuid not null references public.jc_companions(id), channel jc_channel not null, status text not null default 'draft', sent_at timestamptz, response_at timestamptz, response_note text, created_at timestamptz not null default now());
create table if not exists public.jc_bookings (id uuid primary key default gen_random_uuid(), reference text unique not null, request_id uuid not null references public.jc_requests(id), companion_id uuid references public.jc_companions(id), service_amount numeric(10,2) not null default 0, approved_expenses numeric(10,2) not null default 0, total_amount numeric(10,2) generated always as (service_amount + approved_expenses) stored, companion_payout numeric(10,2) not null default 0, status jc_booking_status not null default 'draft', confirmed_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.jc_payments (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.jc_bookings(id) on delete cascade, method text, provider_reference text, amount numeric(10,2) not null, status text not null default 'pending', verified_at timestamptz, notes text, created_at timestamptz not null default now());
create table if not exists public.jc_expenses (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.jc_bookings(id) on delete cascade, category text not null, description text, amount numeric(10,2) not null, approved boolean not null default false, paid_status text not null default 'pending');
create table if not exists public.jc_checkins (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.jc_bookings(id) on delete cascade, checkin_at timestamptz, checkout_at timestamptz, companion_note text, customer_confirmed boolean not null default false, incident_flag boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.jc_message_log (id uuid primary key default gen_random_uuid(), request_id uuid references public.jc_requests(id), companion_id uuid references public.jc_companions(id), channel jc_channel not null, direction text not null default 'outbound', message_type text not null, delivery_status text not null default 'queued', external_reference text, sent_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.jc_admin_audit_log (id uuid primary key default gen_random_uuid(), actor_id uuid references auth.users(id), action text not null, entity_type text, entity_id uuid, detail jsonb, created_at timestamptz not null default now());
create or replace function public.jc_is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.jc_admin_users where user_id=auth.uid()); $$;
alter table public.jc_admin_users enable row level security;
create policy "admins read admin users" on public.jc_admin_users for select using (public.jc_is_admin());
-- All operations data is private to approved admins.
DO $$ declare t text; begin foreach t in array array['jc_customers','jc_requests','jc_request_attachments','jc_companions','jc_opportunities','jc_bookings','jc_payments','jc_expenses','jc_checkins','jc_message_log','jc_admin_audit_log'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "admin full access %1$s" on public.%1$s for all using (public.jc_is_admin()) with check (public.jc_is_admin())',t); end loop; end $$;
insert into storage.buckets (id,name,public) values ('jc-private','jc-private',false) on conflict (id) do nothing;
create policy "admins access private JC files" on storage.objects for all using (bucket_id='jc-private' and public.jc_is_admin()) with check (bucket_id='jc-private' and public.jc_is_admin());
create or replace function public.jc_submit_request(p_full_name text,p_contact text,p_for_self boolean,p_activity text,p_requested_date date default null,p_requested_start_time time default null,p_duration_hours numeric default null,p_general_area text default null,p_destination text default null,p_spending_type text default null,p_companion_cost_plan text default null,p_notes text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_customer public.jc_customers; v_request public.jc_requests; v_email text; v_phone text; begin if coalesce(length(trim(p_full_name)),0)<2 or coalesce(length(trim(p_contact)),0)<5 then raise exception 'Name and contact are required'; end if; if position('@' in p_contact)>1 then v_email:=lower(trim(p_contact)); else v_phone:=trim(p_contact); end if; insert into public.jc_customers(full_name,email,phone,for_self) values(trim(p_full_name),v_email,v_phone,coalesce(p_for_self,true)) returning * into v_customer; insert into public.jc_requests(customer_id,activity,requested_date,requested_start_time,duration_hours,general_area,destination,spending_type,companion_cost_plan,notes) values(v_customer.id,trim(p_activity),p_requested_date,p_requested_start_time,p_duration_hours,trim(p_general_area),trim(p_destination),trim(p_spending_type),trim(p_companion_cost_plan),trim(p_notes)) returning * into v_request; return jsonb_build_object('reference',v_request.reference,'request_id',v_request.id); end $$;
revoke all on function public.jc_submit_request(text,text,boolean,text,date,time,numeric,text,text,text,text,text) from public; grant execute on function public.jc_submit_request(text,text,boolean,text,date,time,numeric,text,text,text,text,text) to anon,authenticated;
create or replace function public.jc_claim_first_admin() returns boolean language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null then return false; end if; if lower(coalesce(auth.jwt()->>'email','')) <> 'priscillanarine@gmail.com' then return false; end if; if exists(select 1 from public.jc_admin_users) then return exists(select 1 from public.jc_admin_users where user_id=auth.uid()); end if; insert into public.jc_admin_users(user_id,display_name) values(auth.uid(),split_part(coalesce(auth.jwt()->>'email','admin'),'@',1)) on conflict do nothing; return true; end $$;
revoke all on function public.jc_claim_first_admin() from public; grant execute on function public.jc_claim_first_admin() to anon,authenticated;

alter table public.jc_customers add column if not exists whatsapp text, add column if not exists telegram text, add column if not exists preferred_contact_method text;
alter table public.jc_requests add column if not exists venue_type text, add column if not exists venue_name text, add column if not exists maps_url text, add column if not exists emergency_contact_name text, add column if not exists emergency_contact_phone text;
create or replace function public.jc_submit_request(p_full_name text,p_contact text,p_for_self boolean,p_activity text,p_requested_date date default null,p_requested_start_time time default null,p_duration_hours numeric default null,p_general_area text default null,p_destination text default null,p_spending_type text default null,p_companion_cost_plan text default null,p_notes text default null,p_venue_type text default null,p_venue_name text default null,p_maps_url text default null,p_whatsapp text default null,p_telegram text default null,p_preferred_channel text default null,p_emergency_contact_name text default null,p_emergency_contact_phone text default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_customer public.jc_customers; v_request public.jc_requests; v_email text; v_phone text; begin if coalesce(length(trim(p_full_name)),0)<2 or coalesce(length(trim(p_contact)),0)<5 then raise exception 'Name and contact are required'; end if; if p_for_self and (coalesce(length(trim(p_emergency_contact_name)),0)<2 or coalesce(length(trim(p_emergency_contact_phone)),0)<5) then raise exception 'An emergency contact is required for a self request'; end if; if position('@' in p_contact)>1 then v_email:=lower(trim(p_contact)); else v_phone:=trim(p_contact); end if; insert into public.jc_customers(full_name,email,phone,whatsapp,telegram,preferred_channel,preferred_contact_method,for_self) values(trim(p_full_name),v_email,v_phone,trim(p_whatsapp),trim(p_telegram),case when lower(trim(p_preferred_channel)) in ('telegram','whatsapp','email') then lower(trim(p_preferred_channel))::jc_channel else null end,trim(p_preferred_channel),coalesce(p_for_self,true)) returning * into v_customer; insert into public.jc_requests(customer_id,activity,requested_date,requested_start_time,duration_hours,general_area,destination,spending_type,companion_cost_plan,notes,venue_type,venue_name,maps_url,emergency_contact_name,emergency_contact_phone) values(v_customer.id,trim(p_activity),p_requested_date,p_requested_start_time,p_duration_hours,trim(p_general_area),trim(p_destination),trim(p_spending_type),trim(p_companion_cost_plan),trim(p_notes),trim(p_venue_type),trim(p_venue_name),trim(p_maps_url),trim(p_emergency_contact_name),trim(p_emergency_contact_phone)) returning * into v_request; return jsonb_build_object('reference',v_request.reference,'request_id',v_request.id); end $$;
revoke all on function public.jc_submit_request(text,text,boolean,text,date,time,numeric,text,text,text,text,text,text,text,text,text,text,text,text,text) from public; grant execute on function public.jc_submit_request(text,text,boolean,text,date,time,numeric,text,text,text,text,text,text,text,text,text,text,text,text,text) to anon,authenticated;
create or replace function public.jc_attach_intake_file(p_request_id uuid,p_storage_path text,p_attachment_type text) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin if p_storage_path not like 'intake/%' or p_attachment_type not in ('id','selfie') then raise exception 'Invalid intake file'; end if; insert into public.jc_request_attachments(request_id,storage_path,attachment_type) values(p_request_id,p_storage_path,p_attachment_type) returning id into v_id; return v_id; end $$;
revoke all on function public.jc_attach_intake_file(uuid,text,text) from public; grant execute on function public.jc_attach_intake_file(uuid,text,text) to anon,authenticated;
drop policy if exists "public intake upload only" on storage.objects;
create policy "public intake upload only" on storage.objects for insert to anon,authenticated with check (bucket_id='jc-private' and name like 'intake/%');

alter table public.jc_requests add column if not exists terms_accepted_at timestamptz, add column if not exists terms_version text, add column if not exists privacy_accepted_at timestamptz;
create or replace function public.jc_submit_request(p_full_name text,p_contact text,p_for_self boolean,p_activity text,p_requested_date date default null,p_requested_start_time time default null,p_duration_hours numeric default null,p_general_area text default null,p_destination text default null,p_spending_type text default null,p_companion_cost_plan text default null,p_notes text default null,p_venue_type text default null,p_venue_name text default null,p_maps_url text default null,p_whatsapp text default null,p_telegram text default null,p_preferred_channel text default null,p_emergency_contact_name text default null,p_emergency_contact_phone text default null,p_terms_accepted boolean default false,p_privacy_accepted boolean default false) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_customer public.jc_customers; v_request public.jc_requests; v_email text; v_phone text; begin if not p_terms_accepted or not p_privacy_accepted then raise exception 'Terms and privacy acceptance are required'; end if; if coalesce(length(trim(p_full_name)),0)<2 or coalesce(length(trim(p_contact)),0)<5 then raise exception 'Name and contact are required'; end if; if p_for_self and (coalesce(length(trim(p_emergency_contact_name)),0)<2 or coalesce(length(trim(p_emergency_contact_phone)),0)<5) then raise exception 'An emergency contact is required for a self request'; end if; if position('@' in p_contact)>1 then v_email:=lower(trim(p_contact)); else v_phone:=trim(p_contact); end if; insert into public.jc_customers(full_name,email,phone,whatsapp,telegram,preferred_channel,preferred_contact_method,for_self) values(trim(p_full_name),v_email,v_phone,trim(p_whatsapp),trim(p_telegram),case when lower(trim(p_preferred_channel)) in ('telegram','whatsapp','email') then lower(trim(p_preferred_channel))::jc_channel else null end,trim(p_preferred_channel),coalesce(p_for_self,true)) returning * into v_customer; insert into public.jc_requests(customer_id,activity,requested_date,requested_start_time,duration_hours,general_area,destination,spending_type,companion_cost_plan,notes,venue_type,venue_name,maps_url,emergency_contact_name,emergency_contact_phone,terms_accepted_at,privacy_accepted_at,terms_version) values(v_customer.id,trim(p_activity),p_requested_date,p_requested_start_time,p_duration_hours,trim(p_general_area),trim(p_destination),trim(p_spending_type),trim(p_companion_cost_plan),trim(p_notes),trim(p_venue_type),trim(p_venue_name),trim(p_maps_url),trim(p_emergency_contact_name),trim(p_emergency_contact_phone),now(),now(),'customer-terms-v1') returning * into v_request; return jsonb_build_object('reference',v_request.reference,'request_id',v_request.id); end $$;
revoke all on function public.jc_submit_request(text,text,boolean,text,date,time,numeric,text,text,text,text,text,text,text,text,text,text,text,text,text,boolean,boolean) from public; grant execute on function public.jc_submit_request(text,text,boolean,text,date,time,numeric,text,text,text,text,text,text,text,text,text,text,text,text,text,boolean,boolean) to anon,authenticated;
